# Generated by Django 5.0.1 on 2025-07-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL for the opportunity card'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Logo URL for the opportunity provider'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='offer_details',
            field=models.JSONField(default=dict, help_text='Specific offer details like discount, validity, etc.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_hash',
            field=models.CharField(blank=True, help_text='Hash to prevent duplicates', max_length=64),
        ),
    ]
