from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def budget_notes(request):
    """
    Return AI-generated budget notes for different categories.
    This is a placeholder implementation that returns sample data.
    """
    # Sample budget notes - in a real implementation, this would be generated by AI
    sample_notes = {
        "Food & Dining": "You're doing well with your food budget! Consider meal planning to save even more money.",
        "Transportation": "Your transportation costs are within budget. Great job managing your expenses!",
        "Shopping": "You're close to your shopping spending limit. Consider waiting for sales before making purchases.",
        "Entertainment": "Entertainment spending is on track. You've earned some fun while staying within budget!",
        "Bills & Utilities": "All utility bills are paid on time. Excellent financial discipline!",
        "Healthcare": "Healthcare expenses are well managed. Keep saving for future medical costs!"
    }
    
    return Response(sample_notes, status=status.HTTP_200_OK)