/**
 * Mock Investment Data
 * 
 * This file contains mock data for investments used in development and testing.
 * Only loaded when __DEV__ is true.
 */

import { TradableAsset } from '../types';

export const mockInvestments: TradableAsset[] = [
  {
    id: 'inv-1',
    name: 'Tesla Inc.',
    symbol: 'TSLA',
    assetType: 'stock',
    exchange: 'NASDAQ',
    currency: 'USD',
    quantity: 3,
    averagePurchasePrice: 700,
    currentPrice: 800,
    totalValue: 2400,
    dailyChange: 15,
    dailyChangePercent: 1.91,
    totalGainLoss: 300,
    totalGainLossPercent: 14.29,
    chartData: [],
    lastUpdated: '2024-01-15T10:00:00Z',
    aiAnalysis: 'High growth potential with innovative technology leadership.',
    riskLevel: 'high',
    recommendation: 'buy',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    sector: 'Automotive',
    logoUrl: 'https://logo.clearbit.com/tesla.com',
    volume: '1.5M',
    marketCap: 750000000000,
    growthRate: 35.0,
  },
  {
    id: 'inv-2',
    name: 'Amazon.com Inc.',
    symbol: 'AMZN',
    assetType: 'stock',
    exchange: 'NASDAQ',
    currency: 'USD',
    quantity: 8,
    averagePurchasePrice: 140,
    currentPrice: 155,
    totalValue: 1240,
    dailyChange: 3,
    dailyChangePercent: 1.97,
    totalGainLoss: 120,
    totalGainLossPercent: 10.71,
    chartData: [],
    lastUpdated: '2024-01-15T10:00:00Z',
    aiAnalysis: 'Solid e-commerce leader with cloud computing dominance.',
    riskLevel: 'medium',
    recommendation: 'hold',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    sector: 'Technology',
    logoUrl: 'https://logo.clearbit.com/amazon.com',
    volume: '900K',
    marketCap: 1500000000000,
    growthRate: 15.5,
  },
  {
    id: 'inv-3',
    name: 'Ethereum',
    symbol: 'ETH',
    assetType: 'crypto',
    exchange: 'Coinbase',
    currency: 'USD',
    quantity: 2,
    averagePurchasePrice: 2500,
    currentPrice: 2800,
    totalValue: 5600,
    dailyChange: 100,
    dailyChangePercent: 3.7,
    totalGainLoss: 600,
    totalGainLossPercent: 12.0,
    chartData: [],
    lastUpdated: '2024-01-15T10:00:00Z',
    aiAnalysis: 'Leading smart contract platform with strong developer ecosystem.',
    riskLevel: 'high',
    recommendation: 'hold',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    sector: 'Cryptocurrency',
    volume: '1.8M',
    marketCap: 320000000000,
    growthRate: 28.0,
  },
  {
    id: 'inv-4',
    name: 'Vanguard S&P 500 ETF',
    symbol: 'VOO',
    assetType: 'etf',
    exchange: 'NYSE',
    currency: 'USD',
    quantity: 15,
    averagePurchasePrice: 400,
    currentPrice: 430,
    totalValue: 6450,
    dailyChange: 5,
    dailyChangePercent: 1.18,
    totalGainLoss: 450,
    totalGainLossPercent: 7.5,
    chartData: [],
    lastUpdated: '2024-01-15T10:00:00Z',
    aiAnalysis: 'Diversified index fund with low fees and steady returns.',
    riskLevel: 'low',
    recommendation: 'buy',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    sector: 'Index Fund',
    volume: '500K',
    marketCap: 850000000000,
    growthRate: 8.5,
  },
];

// Only export mock data in development
export const getInvestmentMocks = (): TradableAsset[] => {
  if (__DEV__) {
    return mockInvestments;
  }
  return [];
};
