# Generated by Django 5.2.3 on 2025-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='custom_input_prompt',
            field=models.CharField(blank=True, help_text="Prompt for the custom input field, e.g., 'Enter amount'.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('TX', 'Text Input'), ('NU', 'Number Input')], default='SC', max_length=2),
        ),
    ]
