# Generated by Django 5.2.3 on 2025-07-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_question_custom_input_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='expense_data',
            field=models.JSONField(blank=True, help_text='Stores structured expense data for the expenses question.', null=True),
        ),
    ]
