# Generated by Django 5.2.3 on 2025-07-07 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(db_index=True, help_text="e.g., 'upi_notification'", max_length=100)),
                ('app', models.CharField(help_text="The name of the source application, e.g., 'paytm'", max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('big_text', models.TextField(blank=True, help_text='The extended text content of the notification, if available.', null=True)),
                ('posted_time', models.DateTimeField(help_text='The original timestamp of the notification.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_time'],
            },
        ),
    ]
