# Generated by Django 5.2.3 on 2025-07-08 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(help_text='Raw body/content of the SMS message')),
                ('received_at', models.DateTimeField(help_text='Timestamp when the SMS was originally received on the device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the message has been parsed and processed by other services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['user', 'received_at'], name='sms_smsmess_user_id_12d58f_idx')],
            },
        ),
    ]
