# Generated by Django 5.2.3 on 2025-07-31 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chartdata',
            name='unique_investment_date',
        ),
        migrations.RemoveConstraint(
            model_name='investment',
            name='unique_user_symbol',
        ),
        migrations.AlterUniqueTogether(
            name='chartdata',
            unique_together={('investment', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('user', 'symbol')},
        ),
    ]
