# Generated by Django 5.2.5 on 2025-08-14 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_remove_chartdata_unique_investment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='investment',
            name='data_enriched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='enrichment_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='enrichment_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='fifty_two_week_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='fifty_two_week_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='volume',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('crypto', 'Cryptocurrency'), ('bond', 'Bond'), ('gold', 'Gold'), ('silver', 'Silver'), ('commodity', 'Commodity')], default='stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='exchange',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='investment',
            name='symbol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('user', 'symbol', 'asset_type')},
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'asset_type'], name='investments_user_id_1714aa_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'created_at'], name='investments_user_id_e56feb_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['symbol'], name='investments_symbol_81b26b_idx'),
        ),
    ]
