# Generated by Django 5.2.5 on 2025-08-22 18:22

from django.db import migrations, models, connection


def check_column_exists(table_name, column_name):
    """Check if a column exists in the given table"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = %s
        """, [table_name, column_name])
        return cursor.fetchone() is not None


def remove_dividend_yield_if_exists(apps, schema_editor):
    """Remove dividend_yield field only if it exists"""
    if check_column_exists('investments_investment', 'dividend_yield'):
        schema_editor.execute('ALTER TABLE investments_investment DROP COLUMN dividend_yield')


def add_dividend_yield_if_not_exists(apps, schema_editor):
    """Add dividend_yield field back (for reverse migration)"""
    if not check_column_exists('investments_investment', 'dividend_yield'):
        schema_editor.execute(
            'ALTER TABLE investments_investment ADD COLUMN dividend_yield DECIMAL(8,4) DEFAULT 0'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_add_performance_indexes'),
    ]

    operations = [
        # Safe removal of dividend_yield field
        migrations.RunPython(
            remove_dividend_yield_if_exists,
            add_dividend_yield_if_not_exists
        ),
        # Alter the exchange field
        migrations.AlterField(
            model_name='investment',
            name='exchange',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
