# Generated by Django 5.0.1 on 2025-08-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_remove_investment_dividend_yield_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='dividend_yield',
        ),
    ]
