# Generated by Django 5.2.5 on 2025-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_remove_investment_dividend_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='ohlc_data',
            field=models.JSONField(blank=True, default=list, help_text='OHLC data with timestamps for line chart display'),
        ),
        migrations.AddField(
            model_name='investment',
            name='ohlc_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time OHLC data was fetched', null=True),
        ),
    ]
