# Generated by Django 5.2.5 on 2025-08-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_add_ohlc_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='enhanced_data_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time enhanced market data (PE ratio, market cap, etc.) was fetched', null=True),
        ),
    ]
