# Generated by Django 5.2.5 on 2025-08-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_add_centralized_market_data_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('crypto', 'Cryptocurrency'), ('bond', 'Bond'), ('gold', 'Gold'), ('silver', 'Silver'), ('commodity', 'Commodity')], max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this symbol should be updated in scheduled tasks')),
                ('first_requested', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('update_frequency', models.IntegerField(default=1, help_text='How often this symbol is requested (for prioritization)')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'asset_type'], name='investments_symbol_188d26_idx'), models.Index(fields=['asset_type', 'is_active'], name='investments_asset_t_647813_idx'), models.Index(fields=['last_updated'], name='investments_last_up_a71164_idx')],
                'unique_together': {('symbol', 'asset_type')},
            },
        ),
        migrations.CreateModel(
            name='DataFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('ohlc_fetch', 'OHLC Data Fetch'), ('market_data_fetch', 'Market Data Fetch'), ('daily_update', 'Daily Data Update'), ('emergency_update', 'Emergency Data Update')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('symbols_requested', models.JSONField(default=list, help_text='List of symbols requested')),
                ('symbols_successful', models.JSONField(default=list, help_text='List of symbols successfully updated')),
                ('symbols_failed', models.JSONField(default=list, help_text='List of symbols that failed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('total_symbols', models.IntegerField(default=0)),
                ('successful_symbols', models.IntegerField(default=0)),
                ('failed_symbols', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['operation_type', 'status'], name='investments_operati_6748c7_idx'), models.Index(fields=['started_at'], name='investments_started_dcdb7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CentralizedMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('asset_type', models.CharField(db_index=True, max_length=20)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume', models.CharField(blank=True, max_length=20, null=True)),
                ('volume_raw', models.BigIntegerField(blank=True, null=True)),
                ('fifty_two_week_high', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('fifty_two_week_low', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_source', models.CharField(default='bharatsm', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_completeness_score', models.IntegerField(default=0, help_text='Score out of 100 for data completeness')),
                ('is_stale', models.BooleanField(default=False)),
                ('asset_symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='investments.assetsymbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'asset_type'], name='investments_symbol_ebe1dd_idx'), models.Index(fields=['last_updated'], name='investments_last_up_216bdc_idx'), models.Index(fields=['sector'], name='investments_sector_890c5c_idx')],
                'unique_together': {('symbol', 'asset_type')},
            },
        ),
        migrations.CreateModel(
            name='CentralizedOHLCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('asset_type', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(choices=[('1Day', '1 Day'), ('1Hour', '1 Hour'), ('30Min', '30 Minutes'), ('15Min', '15 Minutes'), ('5Min', '5 Minutes')], default='1Day', max_length=10)),
                ('ohlc_data', models.JSONField(default=list, help_text="OHLC data with timestamps: [{'timestamp': '2024-01-01', 'open': 100, 'high': 105, 'low': 95, 'close': 102, 'volume': 1000}, ...]")),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('daily_change', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('daily_change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('data_source', models.CharField(default='bharatsm', help_text='Source of the data (bharatsm, perplexity, finnhub, etc.)', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_points_count', models.IntegerField(default=0, help_text='Number of data points in OHLC data')),
                ('is_stale', models.BooleanField(default=False, help_text='Whether the data is considered stale')),
                ('asset_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlc_data', to='investments.assetsymbol')),
            ],
            options={
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['symbol', 'asset_type', 'timeframe'], name='investments_symbol_bb9a57_idx'), models.Index(fields=['last_updated'], name='investments_last_up_eefd2d_idx'), models.Index(fields=['asset_type', 'is_stale'], name='investments_asset_t_c2ffa8_idx')],
                'unique_together': {('symbol', 'asset_type', 'timeframe')},
            },
        ),
    ]
