# Generated by Django 5.0.1 on 2025-08-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_add_centralized_market_data_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralizedmarketdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centralizedmarketdata',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centralizedmarketdata',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centralizedohlcdata',
            name='timeframe',
            field=models.CharField(choices=[('1Day', '1 Day')], default='1Day', max_length=10),
        ),
    ]
